export const mockItems = [
  {
    id: "case-001",
    type: "lost",
    title: "Vintage Leather Briefcase",
    category: "Personal Effects",
    location: "Main Library Reading Room",
    date: "2026-07-28",
    description: "Dark brown calfskin leather with brass latches. Contains research documents.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "case-002",
    type: "found",
    title: "Signet Ring (Gold)",
    category: "Jewelry & Valuables",
    location: "Faculty Club Courtyard",
    date: "2026-07-29",
    description: "Engraved gold signet ring found near the fountain. Handed to security.",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "case-003",
    type: "lost",
    title: "Fountain Pen Set",
    category: "Stationery",
    location: "Auditorium Hall B",
    date: "2026-07-30",
    description: "Classic black pen with gold trim inside a green velvet pouch.",
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=400",
  },
];